version: "3"

services: 
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://azure-mongodb-granja:hZFGnpIxvW37tgv9yVYq8oCCaFp8fGDVXAqIy8WqaoO2CZ7Co6VFOGD9tnpn4LDdoia29qOG8Rl9vo5P6xVI3g%3D%3D@azure-mongodb-granja.mongo.cosmos.azure.com:10255/dbgranja?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@azure-mongodb-granja@
      - MONGO_URI_DEV=mongodb+srv://AlexSinMas:1231212_@cluster0.gwz1u.mongodb.net/shareyouridea?retryWrites=true&w=majority
      - APPLICATION_NAME=api-granja
      - JWT_SECRET=4l3x4nd3r82@_
      - CACHE_KEY=myStrongPassword
      - SWAGGER_DOC=swagger
      - SWAGGER_PROD=swagger
    ports:
      - "8080:8080"

  mongo:
    image: mongo